/** Curso de muestra completo — Prótesis fija estética anterior */
export const SAMPLE_COURSE_ID = "c-demo";
export const DEMO_STUDENT_EMAIL = "cursos@alumno.com";

const COVER =
  "https://static.wixstatic.com/media/aca030_c3d4df8430f040f9a2e65c4b80077a66~mv2.jpg";

export function getSampleCourseRaw() {
  return {
    id: SAMPLE_COURSE_ID,
    title: "Prótesis fija estética anterior",
    subtitle: "Del diagnóstico al acabado de alta gama en laboratorio",
    shortDescription:
      "Formación integral en estética anterior: planificación, estratificación cerámica, caracterización y protocolos de laboratorio Vallodental.",
    category: "Estética",
    level: "Intermedio",
    language: "Español",
    instructor: "Alfredo Vallo",
    tags: ["estética", "cerámica", "anterior", "laboratorio"],
    status: "published",
    price: 390,
    durationHours: 18,
    accentColor: "#c9a96e",
    coverImage: COVER,
    bannerImage: COVER,
    thumbnail: COVER,
    trailerUrl: "",
    blocks: [
      {
        id: "bd1",
        type: "heading",
        text: "Lo que aprenderás",
        size: "lg",
        color: "#c9a96e",
        align: "left",
      },
      {
        id: "bd2",
        type: "list",
        items: [
          "Planificar casos de estética anterior con criterio biomimético",
          "Dominar capas de dentina, esmalte y efectos superficiales",
          "Aplicar protocolos de caracterización en casos reales",
          "Entregar prótesis listas para prueba clínica",
        ],
        color: "#f0ece4",
        align: "left",
      },
      {
        id: "bd3",
        type: "callout",
        text: "💎 Incluye actividades prácticas, casos clínicos y examen final evaluable.",
        color: "#e8d5b0",
        bgColor: "rgba(201,169,110,0.12)",
        align: "left",
      },
    ],
    items: [],
    structure: [
      {
        id: "m1",
        title: "Módulo 1 · Fundamentos",
        published: true,
        unlockDays: 0,
        items: [],
        topics: [
          {
            id: "t1",
            title: "Introducción y materiales",
            published: true,
            items: [
              {
                kind: "lesson",
                id: "l1",
                title: "Bienvenida al curso",
                published: true,
                durationMin: 12,
                videoUrl: "",
                unlock: { mode: "open", date: null },
                blocks: [
                  {
                    id: "b1",
                    type: "heading",
                    text: "Bienvenido a Vallodental Academy",
                    size: "lg",
                    color: "#c9a96e",
                    align: "left",
                  },
                  {
                    id: "b2",
                    type: "paragraph",
                    text: "En este curso trabajarás con los mismos protocolos que aplicamos en laboratorio para casos de estética anterior de alta complejidad. Cada lección combina teoría aplicada, vídeo demostrativo y actividades prácticas.",
                    color: "#f0ece4",
                    align: "left",
                  },
                  {
                    id: "b3",
                    type: "emoji",
                    emoji: "🦷",
                    size: "48",
                    align: "center",
                  },
                  {
                    id: "b4",
                    type: "callout",
                    text: "🎯 Objetivo del módulo: sentar las bases técnicas antes de entrar en estratificación avanzada.",
                    color: "#e8d5b0",
                    bgColor: "rgba(201,169,110,0.12)",
                    align: "left",
                  },
                ],
                assignment: null,
                quiz: null,
              },
              {
                kind: "activity",
                id: "act1",
                title: "Autoevaluación inicial",
                published: true,
                activityType: "practice",
                durationMin: 10,
                instructions:
                  "Responde por escrito: ¿Cuántos casos de estética anterior realizas al mes? ¿Cuál es tu mayor dificultad actual?",
                unlock: { mode: "sequential", date: null },
                blocks: [
                  {
                    id: "ba1",
                    type: "paragraph",
                    text: "Esta actividad nos ayuda a personalizar tu recorrido. Sé honesto: no hay respuestas incorrectas.",
                    color: "#f0ece4",
                    align: "left",
                  },
                ],
                assignment: {
                  id: "as1",
                  title: "Reflexión inicial",
                  instructions: "Responde con honestidad. El profesor revisará tus respuestas escritas.",
                  dueDate: "",
                  maxScore: 100,
                  passScore: 60,
                  allowFiles: false,
                  fileTypes: [],
                  questions: [
                    {
                      id: "aq1",
                      type: "text",
                      text: "¿Cuántos casos de estética anterior realizas al mes? Describe tu experiencia (150-300 palabras).",
                      points: 50,
                      required: true,
                      options: [],
                      correct: 0,
                    },
                    {
                      id: "aq2",
                      type: "text",
                      text: "¿Cuál es tu mayor dificultad actual en estética anterior?",
                      points: 50,
                      required: true,
                      options: [],
                      correct: 0,
                    },
                  ],
                },
              },
              {
                kind: "lesson",
                id: "l2",
                title: "Materiales cerámicos y equipamiento",
                published: true,
                durationMin: 18,
                videoUrl: "",
                unlock: { mode: "sequential", date: null },
                blocks: [
                  {
                    id: "b5",
                    type: "subheading",
                    text: "Kit esencial de laboratorio",
                    size: "md",
                    color: "#e8d5b0",
                    align: "left",
                  },
                  {
                    id: "b6",
                    type: "list",
                    items: [
                      "Cerámicas dentina / esmalte compatibles con tu horno",
                      "Pinceles de filamento sintético calibres 0 y 1",
                      "Lupas o microscopio según protocolo del centro",
                      "Iluminación polarizada para control de value",
                    ],
                    color: "#f0ece4",
                    align: "left",
                  },
                  {
                    id: "b7",
                    type: "table",
                    headers: ["Material", "Función"],
                    rows: [
                      ["Dentina A2", "Cuerpo y cromatismo"],
                      ["Esmalte translúcido", "Superficie y efectos ópticos"],
                      ["Mamelones opalescentes", "Zona incisal y juventud"],
                    ],
                    align: "left",
                  },
                ],
                assignment: null,
                quiz: null,
              },
            ],
          },
          {
            id: "t2",
            title: "Protocolo clínico-laboratorio",
            published: true,
            items: [
              {
                kind: "lesson",
                id: "l3",
                title: "Flujo de trabajo en 6 pasos",
                published: true,
                durationMin: 15,
                videoUrl: "",
                unlock: { mode: "sequential", date: null },
                blocks: [
                  {
                    id: "b8",
                    type: "paragraph",
                    text: "El éxito en estética anterior no depende solo del acabado final: depende de un flujo coherente desde la toma de color hasta la entrega en clínica.",
                    color: "#f0ece4",
                    align: "left",
                  },
                  {
                    id: "b9",
                    type: "accordion",
                    items: [
                      { title: "1. Diagnóstico y foto-protocolo", body: "Registro extraoral e intraoral estandarizado." },
                      { title: "2. Preparación del modelo", body: "Montaje en articulador y registro de recortes." },
                      { title: "3. Estratificación", body: "Capas de dentina y esmalte con control de espesor." },
                      { title: "4. Caracterización", body: "Fisuras, opalescencia y efectos de value." },
                      { title: "5. Acabado y brillo", body: "Pulido mecánico y control final con luz polarizada." },
                      { title: "6. Prueba clínica", body: "Ajuste oclusal y protocolo de cementado." },
                    ],
                    align: "left",
                  },
                ],
                assignment: null,
                quiz: null,
              },
              {
                kind: "activity",
                id: "act2",
                title: "Caso clínico: planificación",
                published: true,
                activityType: "case",
                durationMin: 25,
                instructions:
                  "Analiza el caso propuesto. Identifica zona cervical, medio e incisal. Indica qué efectos aplicarías en cada tercio.",
                unlock: { mode: "sequential", date: null },
                blocks: [
                  {
                    id: "ba2",
                    type: "alert",
                    text: "⚠ Caso: paciente 32 años, diastemas cerrados, deseaba BL2 natural con translucidez incisal marcada.",
                    variant: "warning",
                    align: "left",
                  },
                  {
                    id: "ba3",
                    type: "image",
                    url: COVER,
                    caption: "Referencia estética de laboratorio",
                    alt: "Caso estética",
                    align: "left",
                  },
                ],
                assignment: {
                  id: "as2",
                  title: "Entrega del plan de caracterización",
                  instructions: "Sube un PDF o imagen con tu esquema de estratificación por tercios.",
                  dueDate: "",
                  maxScore: 100,
                  allowFiles: true,
                  fileTypes: ["pdf", "jpg", "png"],
                },
              },
              {
                kind: "exam",
                id: "ex1",
                title: "Examen · Módulo 1",
                published: true,
                instructions: "Demuestra que dominas los fundamentos antes de pasar al módulo avanzado. Necesitas 70% para aprobar.",
                blocks: [],
                timeLimitMin: 20,
                maxAttempts: 3,
                passScore: 70,
                shuffleQuestions: false,
                unlock: { mode: "sequential", date: null },
                questions: [
                  {
                    id: "q1",
                    type: "single",
                    text: "¿Qué capa aporta principalmente el cromatismo en estética anterior?",
                    options: ["Esmalte superficial", "Dentina", "Adhesivo", "Opaca"],
                    correct: 1,
                    points: 10,
                  },
                  {
                    id: "q2",
                    type: "single",
                    text: "¿Para qué sirve la luz polarizada en acabado cerámico?",
                    options: [
                      "Endurecer la cerámica",
                      "Controlar value y uniformidad óptica",
                      "Sustituir el horno",
                      "Eliminar el pulido",
                    ],
                    correct: 1,
                    points: 10,
                  },
                  {
                    id: "q3",
                    type: "bool",
                    text: "El flujo Vallodental incluye prueba clínica antes del cementado definitivo.",
                    options: ["Verdadero", "Falso"],
                    correct: 0,
                    points: 10,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "m2",
        title: "Módulo 2 · Estratificación avanzada",
        published: true,
        unlockDays: 0,
        items: [
          {
            kind: "activity",
            id: "actm1",
            title: "Laboratorio: preparación de mezclas",
            published: true,
            activityType: "lab",
            durationMin: 30,
            instructions: "Prepara tres muestras de opalescencia incisal con distinta carga de partículas. Documenta con foto.",
            unlock: { mode: "sequential", date: null },
            blocks: [
              {
                id: "bm1",
                type: "callout",
                text: "🔬 Actividad a nivel de módulo: consolida lo aprendido antes de las lecciones avanzadas.",
                color: "#e8d5b0",
                bgColor: "rgba(201,169,110,0.12)",
                align: "left",
              },
            ],
            assignment: null,
          },
        ],
        topics: [
          {
            id: "t3",
            title: "Estratificación y caracterización",
            published: true,
            items: [
              {
                kind: "lesson",
                id: "l4",
                title: "Capas de dentina y mamelones",
                published: true,
                durationMin: 22,
                videoUrl: "",
                unlock: { mode: "sequential", date: null },
                blocks: [
                  {
                    id: "b10",
                    type: "heading",
                    text: "Construcción en capas",
                    size: "lg",
                    color: "#c9a96e",
                    align: "left",
                  },
                  {
                    id: "b11",
                    type: "paragraph",
                    text: "La dentina crea el volume interno; los mamelones guían la luz en zona incisal. Alterna capas finas y deja reposos según tu cerámica.",
                    color: "#f0ece4",
                    align: "left",
                  },
                  {
                    id: "b12",
                    type: "quote",
                    text: "La estética es óptica antes que color.",
                    color: "#e8d5b0",
                    align: "left",
                  },
                ],
                assignment: null,
                quiz: {
                  id: "qz1",
                  title: "Mini test · Capas",
                  timeLimitMin: 5,
                  maxAttempts: 5,
                  passScore: 60,
                  questions: [
                    {
                      id: "q4",
                      type: "single",
                      text: "¿Dónde se colocan típicamente los mamelones?",
                      options: ["Cervical", "Incisal", "Palatino profundo", "Solo interproximal"],
                      correct: 1,
                      points: 10,
                    },
                  ],
                },
              },
              {
                kind: "lesson",
                id: "l5",
                title: "Caracterización externa y entrega",
                published: true,
                durationMin: 20,
                videoUrl: "",
                unlock: { mode: "sequential", date: null },
                blocks: [
                  {
                    id: "b13",
                    type: "paragraph",
                    text: "Fisuras, decalcificaciones y maquillaje periférico deben ser sutiles. El objetivo es creíble, no espectacular.",
                    color: "#f0ece4",
                    align: "left",
                  },
                  {
                    id: "b14",
                    type: "list",
                    items: [
                      "Control con luz natural y polarizada",
                      "Foto comparativa con guía de color",
                      "Checklist de oclusión y puntos de contacto",
                    ],
                    color: "#f0ece4",
                    align: "left",
                  },
                ],
                assignment: null,
                quiz: null,
              },
              {
                kind: "exam",
                id: "ex2",
                title: "Examen final del curso",
                published: true,
                instructions: "Evaluación global. Aprobar con 75% para obtener certificado.",
                blocks: [],
                timeLimitMin: 30,
                maxAttempts: 2,
                passScore: 75,
                shuffleQuestions: true,
                unlock: { mode: "sequential", date: null },
                questions: [
                  {
                    id: "q5",
                    type: "multi",
                    text: "Selecciona elementos de un acabado premium (varias correctas):",
                    options: [
                      "Control de value",
                      "Caracterización sutil",
                      "Opaca visible en incisal",
                      "Brillo homogéneo",
                    ],
                    correct: [0, 1, 3],
                    points: 15,
                  },
                  {
                    id: "q6",
                    type: "single",
                    text: "¿Qué documento entregaste en la actividad de planificación?",
                    options: ["Radiografía", "Plan de caracterización", "Factura", "Consentimiento"],
                    correct: 1,
                    points: 10,
                  },
                  {
                    id: "q7",
                    type: "single",
                    text: "En el protocolo Vallodental, ¿cuándo tiene lugar la prueba clínica?",
                    options: ["Antes del acabado", "Tras caracterización y antes del cementado", "Nunca", "Solo en implantes"],
                    correct: 1,
                    points: 10,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    settings: {
      sequentialUnlock: true,
      dripContent: false,
      certificateEnabled: true,
      commentsEnabled: true,
    },
    createdAt: "2026-03-01T10:00:00.000Z",
    updatedAt: "2026-03-15T10:00:00.000Z",
  };
}

export function getDemoStudentRaw() {
  return {
    id: "s-demo",
    name: "Alumno Demo",
    email: DEMO_STUDENT_EMAIL,
    status: "active",
    courseIds: [SAMPLE_COURSE_ID],
    createdAt: "2026-03-01T10:00:00.000Z",
  };
}
